name: Windows x64 CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Compile vcpkg dependencies
      run: vcpkg_windows_x64.bat
      shell: cmd
    # This is where GitHub actions on Windows get really nonsensical.
    # MSBuild is not on the path by default, despite this running on a Windows / Visual Studio 2019 docker image.
    # We currently use 3rd party action to avoid hard coding the path to MSBuild.
    # Comedy bonus: GitHub is now owned by Microsoft.
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Compile Duke3D
      run: build_windows_x64.bat
      shell: cmd
